name: build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          install: >
            git
            mingw-w64-x86_64-gcc 
            mingw-w64-x86_64-curl
            libtool
            openssl
            openssl-devel
            python-devel
            pkgconf
            autoconf
            automake
            make
          update: true

      - name: Configure and Build
        shell: msys2 {0}
        run: |
          ;

      - name: Test Executable
        shell: msys2 {0}
        run: |
          ;
